version: '3.8'
name: password_gen-test

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - redis
      - celery

  celery:
    build: ./app
    command: celery -A password_generator worker --loglevel=info
    volumes:
      - ./app:/usr/src/app
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"
